### ISSUE TITLE
EQ 

### ISSUE THREAD

**Issue by maxemillianian** [zettonaender/eqapotographiceq-gui#1]
I used your app to convert a few Peace EQ profiles to Graphic EQ.txt files, and I did so successfully.

I am not aware of anything having changed, but with recent attempts the EQ graph and sound seems off. 

Here is the graph when mapped in Peace:
![image](https://user-images.githubusercontent.com/22266723/113795408-69680e80-977f-11eb-80c7-97e44abae9e5.png)

And here is the graph as imaged in the myresult\ssweep folder:
![image](https://user-images.githubusercontent.com/22266723/113795453-869cdd00-977f-11eb-8fb0-9e1c1ec9cd86.png)

cmd box:
![image](https://user-images.githubusercontent.com/22266723/113795483-9a484380-977f-11eb-94a7-d451f685f0f0.png)

Screenshot of GUI:
![image](https://user-images.githubusercontent.com/22266723/113795792-438f3980-9780-11eb-8f3b-5ed7d61ca1ac.png)

Graphic EQ:
[GraphicEQ.txt](https://github.com/zettonaender/eqapotographiceq-gui/files/6268225/GraphicEQ.txt)

Here's the sweep.csv from the myresult\sweep folder (renamed to a .txt to enable attachment):
[ssweep.txt](https://github.com/zettonaender/eqapotographiceq-gui/files/6268232/ssweep.txt)

Today I updated to the latest version, but the issue persists. 

Any ideas?

**Comment by zettonaender** [comment]
can you pass me the peace.txt from eq apo? thanks

**Comment by zettonaender** [comment]
also what sample rate are you using?

**Comment by zettonaender** [comment]
Oh yeah, before that can you try adding a -15dB preamp in Peace? Thanks.

**Comment by zettonaender** [comment]
Issue with clipping fixed with latest update.
