### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by Rain2784** [zettonaender/eqapotographiceq-gui#2]
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: c:\program files\python39\Include\UNKNOWN
sysconfig: c:\program files\python39\Include
WARNING: Additional context:
user = False
home = None
root = None
prefix = None

**Comment by zettonaender** [comment]
Seems to be a problem with 'pip', can you try `python -m pip install pip==21.0.1` and opening the gui again

**Comment by Rain2784** [comment]
after installing using that command i get this:

WARNING: The scripts pip.exe, pip3.9.exe and pip3.exe are installed in
'C:\Users\sjbon\AppData\Roaming\Python\Python39\Scripts' which is not on
PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this
warning, use --no-warn-script-location.
WARNING: Value for scheme.headers does not match. Please report this to <
https://github.com/pypa/pip/issues/9617>
distutils: C:\Users\sjbon\AppData\Roaming\Python\Python39\Include\UNKNOWN
sysconfig: C:\Users\sjbon\AppData\Roaming\Python\Python39\Include
WARNING: Additional context:
user = True
home = None
root = None
prefix = None

then, if i open the bat file, i get a lot of red letters and it crashes

**Comment by zettonaender** [comment]
Yeah so I suppose I can't really "fix" it since this isn't an issue with the program rather than the newest update of "pip". 

You can try downgrading to Python 3.7 to perhaps fix this issue though, let me know if it works.

**Comment by Rain2784** [comment]
Can you tell me the version of pip to use too? Im going to uninstall and
search for python 3.7

Then try running the program again

**Comment by zettonaender** [comment]
I think the red text you mentioned is because python is building packages instead of installing. Just to be sure, I'm using pip 20.1.1 though.

**Comment by jawadnaseemkhan** [comment]
> WARNING: Value for scheme.headers does not match. Please report this to [pypa/pip#9617](https://github.com/pypa/pip/issues/9617)
> distutils: c:\program files\python39\Include\UNKNOWN
> sysconfig: c:\program files\python39\Include
> WARNING: Additional context:
> user = False
> home = None
> root = None
> prefix = None

**Comment by jawadnaseemkhan** [comment]
Try upgrading the pip by using this command on command prompt using administrative

**pip install --upgrade pip**
