### ISSUE TITLE
Utterly overwhelmed. Whats wrong here

### ISSUE THREAD

**Issue by d3d43** [zettonaender/eqapotographiceq-gui#4]
![image](https://user-images.githubusercontent.com/47383653/141645413-946fe183-241e-47cc-b80c-632fae2f89c7.png)
Can I get some help? pip and python 3.9 as well as numpy is installed

**Comment by d3d43** [comment]
seems to be same result with python 3.7

**Comment by d3d43** [comment]
Never mind, Fixed the initial issue by reinstalling everything, python pip and numpy. Now I have a different issue. When I press "generate"


Traceback (most recent call last):
  File "C:\Users\mini\Downloads\Installers\eqapotographiceq-gui-main\guipeace.py", line 119, in <module>
    dev=device[0]
IndexError: list index out of range

Not sure how to go on and troubleshoot from here

**Comment by Mrsevic** [comment]
Me neither, dunno how can i get it up and running

**Comment by zettonaender** [comment]
Sorry, I was busy with college. Can you try out the new version?

**Comment by tonyzehs** [comment]
It was fiddly. After 2 hours I finally got it working including having Peace enabled during test, switching output devices, manually setting device output format, and uninstalling the Microsoft store version of Python while instead installing instead from their official site.

**Comment by tonyzehs** [comment]
Also, it seems without taking the pre-amplifying into account may result in audio clipping when Wavelet is in action. Not a unique issue with this tool, and can be remedied by adjusting all gain down ahead of exporting.

**Comment by zettonaender** [comment]
Yeah so I believe wavelet always add +6 dB of preamp to anything you import. We can't do anything about this.

A way to fix it is to add negative preamp using the channel balance slider.

**Comment by tonyzehs** [comment]
Another thing I found is if I set the output folder to the same Equalizer EPO folder, the script will finish normally but no file would be written; if I set the output folder to desktop, etc (maybe r/w file access related) the sweep folder would output as normal.

**Comment by zettonaender** [comment]
> Another thing I found is if I set the output folder to the same Equalizer EPO folder, the script will finish normally but no file would be written; if I set the output folder to desktop, etc (maybe r/w file access related) the sweep folder would output as normal.

Correct, the folder needs admin access by default.
