### ISSUE TITLE
Converter seems ignores Preamp

### ISSUE THREAD

**Issue by farsdewibs0n** [zettonaender/eqapotographiceq-gui#6]
Preamp should be implemented because Wavelet lacks Preamp feature

**Comment by zettonaender** [comment]
Sorry for the late reply. If you mean the preamp which makes the max gain less than 0dBFS, the program automatically normalize it. Wavelet adds a +6dB preamp automatically though, so if you want to fix this, use Channel Balance and set both channels to -6dB.

**Comment by farsdewibs0n** [comment]
Understandable, issue fixed
